routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['user']], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');

    // categories
    Route::resource('categories', 'CategoryController');
    Route::prefix('categories')->group(function (){
        Route::get('/delete-or-restore/{category}', 'CategoryController@deleteOrRestore')->name('categories.delete');
    });

    // products
    Route::resource('products', 'ProductController');
    Route::prefix('products')->group(function (){
        Route::get('/delete-or-restore/{product}', 'ProductController@deleteOrRestore')->name('products.delete');
    });

    // purchases
    Route::resource('purchases', 'PurchaseController');
    Route::prefix('purchases')->group(function (){
        Route::get('/delete-or-restore/{purchase}', 'PurchaseController@deleteOrRestore')->name('purchases.delete');
        Route::get('/product-form/{index?}', 'PurchaseController@productForm')->name('purchases.productForm');
    });
});


Route::view('user/login', 'user.login')->name('user.login');
Route::post('user/do-login', 'UserController@doLogin')->name('user.doLogin');

resources/views/purchases/create.blade.php
@extends('layouts.master')

@section('title', 'Create Purchase')

@section('css')
    <link href="{{asset('assets/css/select2.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/css/cropper.css')}}" rel="stylesheet" type="text/css">
    <style>
        span.select2-container{
            width: 100% !important;
        }
    </style>
@endsection

@section('content')
    @include('partials._crop-image-modal')

    <div class="page-heading">
        <h1 class="page-title">Create Purchase</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{route('dashboard')}}"><i class="fa fa-home font-20"></i></a>
            </li>
            <li class="breadcrumb-item">Create Purchase</li>
        </ol>
    </div>

    @include('purchases.form')
@endsection

@section('js')
    <script src="{{asset('assets/js/select2.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/jquery.validate.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/cropper.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/image-cropper-modal.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/purchases.js')}}" type="text/javascript"></script>
@endsection

resources/views/purchases/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Purchase')

@section('css')
    <link href="{{asset('assets/css/select2.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/css/cropper.css')}}" rel="stylesheet" type="text/css">
    <style>
        span.select2-container{
            width: 100% !important;
        }
    </style>
@endsection

@section('content')
    @include('partials._crop-image-modal')

    <div class="page-heading">
        <h1 class="page-title">Edit Purchase</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{route('dashboard')}}"><i class="fa fa-home font-20"></i></a>
            </li>
            <li class="breadcrumb-item">Edit Purchase</li>
        </ol>
    </div>

    @include('purchases.form')
@endsection

@section('js')
    <script src="{{asset('assets/js/select2.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/jquery.validate.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/cropper.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/image-cropper-modal.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/purchases.js')}}" type="text/javascript"></script>
@endsection

resources/views/purchases/form.blade.php
<div class="page-content">
    <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title">{{isset($purchase) ? 'Edit' : 'Create'}} Purchase</div>
        </div>
        <div class="ibox-body">
            <form action="{{isset($purchase) ? route('purchases.update', $purchase['id']) : route('purchases.store')}}" method="post" id="purchaseForm">
                @csrf
                @if(isset($purchase))
                    @method('PUT')
                @endif
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group row">
                            <label for="supplier_id" class="col-sm-3 col-form-label">Supplier:</label>
                            <div class="col-sm-9">
                                <select class="form-control select2_select select2-hidden-accessible" name="supplier_id" id="supplier_id" data-placeholder="Select supplier">
                                    <option></option>
                                    @foreach($suppliers as $supplier)
                                        <option value="{{$supplier->id}}" {{isset($purchase) ? ($purchase['supplier_id'] == $supplier->id ? 'selected' : '') : (old('supplier_id') == $supplier->id ? 'selected' : '')}}>{{$supplier->name}}</option>
                                    @endforeach
                                </select>
                                @include('partials._error', ['field' => 'supplier_id'])
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group required row">
                            <label for="total" class="col-sm-3 col-form-label">Total Price:</label>
                            <div class="col-sm-9">
                                <input class="form-control {{\App\Utils\AppUtils::inputFieldError($errors, 'total')}}" name="total" value="{{isset($purchase) ? $purchase['total'] : old('total')}}" id="total" type="number" placeholder="Total Price">
                                @include('partials._error', ['field' => 'total'])
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <a href="#" class="btn btn-success add-product m-r-5" data-url="{{route('purchases.productForm')}}" data-toggle="tooltip" data-original-title="Add Product"><i class="fa fa-plus font-14"></i></a>
                    </div>
                    <!-- product rows start -->
                    <div class="col-12 border-bottom-0 product-rows-start border"></div>
                    @if(old('product_id'))
                        @foreach(old('product_id') as $key => $value)
                            @include('purchases.product-form', ['index' => $key])
                        @endforeach
                    @elseif(isset($purchase))
                        @foreach($purchase['products'] as $key => $value)
                            @include('purchases.product-form', ['index' => $key, 'prod' => $value])
                        @endforeach
                     @else
                        @include('purchases.product-form', ['index' => 0])
                    @endif
                    <div class="col-12 border-bottom-0 product-rows-end border"></div>
                    <!-- product rows end -->
                    <div class="col-5 mt-3"></div>
                    <div class="col-md-5 mt-3">
                        <div class="form-group mb-0 row">
                            <label class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9">
                                <button type="submit" class="btn btn-primary btn-block">{{isset($purchase) ? 'Update' : 'Create'}} Purchase</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/purchases/index.blade.php
@extends('layouts.master')

@section('title', 'Manage Purchases')

@section('css')
    <link href="{{asset('assets/css/datatables.min.css')}}" rel="stylesheet" />
@endsection

@section('content')
    <div class="page-heading">
        <h1 class="page-title">Manage Purchases</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{route('dashboard')}}"><i class="fa fa-home font-20"></i></a>
            </li>
            <li class="breadcrumb-item">Manage Purchases</li>
        </ol>
    </div>
    <div class="page-content fade-in-up">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">Purchases</div>
            </div>
            <div class="ibox-body">
                <table class="table table-striped table-bordered table-hover" id="category-table" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Supplier</th>
                        <th>Created By</th>
                        <th>Updated By</th>
                        <th>No. of Products</th>
                        <th>Total</th>
                        <th>Created At</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($purchases as $purchase)
                        <tr data-index="{{$purchase['id']}}">
                            <td>{{$purchase['id']}}</td>
                            <td>{{$purchase['supplier']}}</td>
                            <td>{{$purchase['created_by']}}</td>
                            <td>{{$purchase['updated_by']}}</td>
                            <td>{{$purchase['no_of_products']}}</td>
                            <td>{{$purchase['total']}}</td>
                            <td>{{$purchase['created_at']}}</td>
                            <td class="text-center">
                                <a href="{{route('purchases.show', $purchase['id'])}}" class="btn btn-info btn-xs m-r-5" data-toggle="tooltip" data-original-title="View"><i class="fa fa-eye font-14"></i></a>
                                <a href="{{route('purchases.edit', $purchase['id'])}}" class="btn btn-primary btn-xs m-r-5" data-toggle="tooltip" data-original-title="Edit"><i class="fa fa-pencil font-14"></i></a>
                                <a href="{{route('purchases.destroy', $purchase['id'])}}" class="btn btn-danger delete-purchase btn-xs m-r-5" data-toggle="tooltip" data-original-title="Delete"><i class="fa fa-trash font-14"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script src="{{asset('assets/js/datatables.min.js')}}" type="text/javascript"></script>
    <script type="text/javascript">
        let dataTable = $('#category-table').DataTable({
            pageLength: 10,
        });


        $(document).on('click', '.delete-purchase', function (e) {
            e.preventDefault();
            let isDelete = confirm('Do you really want to permanently delete this?');
            if (isDelete){
                let row = $(this).parents('tr');
                let url = $(this).attr('href');
                $.ajax({
                    url: url,
                    type: 'DELETE',
                    success: function (response) {
                        if (JSON.parse(response).status){
                            showToast('Success', JSON.parse(response).message, 'success');
                            dataTable.row(row).remove().draw(false);
                        } else {
                            showToast('Error', JSON.parse(response).message, 'error');
                        }
                    }
                });
            }
        });
    </script>
@endsection

resources/views/purchases/product-form.blade.php
<div class="col-12 product-row border border-top-0 border-left-0 border-right-0 pt-3" data-index="{{$index}}">
    <div class="row">
        <div class="col-md-5">
            <div class="form-group required row {{\App\Utils\AppUtils::formGroupError($errors, 'product_id.'.$index)}}">
                <label for="product_id_{{$index}}" class="col-sm-3 col-form-label">Product:</label>
                <div class="col-sm-9">
                    <select class="form-control unique select2_select select2-hidden-accessible product_id" name="product_id[{{$index}}]" id="product_id_{{$index}}" data-placeholder="Select Product">
                        <option></option>
                        @foreach($products as $product)
                            <option value="{{$product['id']}}" {{isset($prod) ? ($prod['product_id'] == $product['id'] ? 'selected' : '') : (old('product_id.'.$index) == $product['id'] ? 'selected' : '')}}>{{$product['product_name']}}</option>
                        @endforeach
                    </select>
                    @include('partials._error', ['field' => 'product_id.'.$index])
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="form-group required row {{\App\Utils\AppUtils::formGroupError($errors, 'quantity.'.$index)}}">
                <label for="quantity_{{$index}}" class="col-sm-3 col-form-label">Quantity:</label>
                <div class="col-sm-9">
                    <input class="form-control {{\App\Utils\AppUtils::inputFieldError($errors, 'quantity.'.$index)}} quantity" name="quantity[{{$index}}]" value="{{isset($prod) ? $prod['quantity'] : old('quantity.'.$index)}}" id="quantity_{{$index}}" type="number" placeholder="Quantity">
                    @include('partials._error', ['field' => 'quantity.'.$index])
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <a href="#" class="btn btn-danger remove-product mr-3" data-index="{{$index}}" data-toggle="tooltip" data-original-title="Remove Product"><i class="fa fa-minus font-14"></i></a>
        </div>
        <div class="col-md-5">
            <div class="form-group required row {{\App\Utils\AppUtils::formGroupError($errors, 'unit_price.'.$index)}}">
                <label for="unit_price_{{$index}}" class="col-sm-3 col-form-label">Unit Price:</label>
                <div class="col-sm-9">
                    <input class="form-control {{\App\Utils\AppUtils::inputFieldError($errors, 'unit_price.'.$index)}} unit_price" name="unit_price[{{$index}}]" value="{{isset($prod) ? $prod['unit_price'] : old('unit_price.'.$index)}}" id="unit_price_{{$index}}" type="number" placeholder="Unit Price">
                    @include('partials._error', ['field' => 'unit_price.'.$index])
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="form-group required row {{\App\Utils\AppUtils::formGroupError($errors, 'sub_total.'.$index)}}">
                <label for="sub_total_{{$index}}" class="col-sm-3 col-form-label">Sub Total:</label>
                <div class="col-sm-9">
                    <input class="form-control {{\App\Utils\AppUtils::inputFieldError($errors, 'sub_total.'.$index)}} sub_total" name="sub_total[{{$index}}]" value="{{isset($prod) ? $prod['sub_total'] : old('sub_total.'.$index)}}" id="sub_total_{{$index}}" type="number" placeholder="Sub Total">
                    @include('partials._error', ['field' => 'sub_total.'.$index])
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/purchases/show.blade.php
@extends('layouts.master')

@section('title', 'Purchase Detail')

@section('css')
    <link href="{{asset('assets/css/datatables.min.css')}}" rel="stylesheet" />
@endsection

@section('content')
    <div class="page-heading">
        <h1 class="page-title">Purchase Detail</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{route('dashboard')}}"><i class="fa fa-home font-20"></i></a>
            </li>
            <li class="breadcrumb-item">Purchase Detail</li>
        </ol>
    </div>
    <div class="page-content fade-in-up">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title d-flex w-100 justify-content-between">
                    <span>Purchase</span>
                    <a href="{{route('purchases.edit', $purchase['id'])}}" class="btn btn-primary btn-xs m-r-5" data-toggle="tooltip" data-original-title="Edit"><i class="fa fa-pencil font-14"></i></a>
                </div>
            </div>
            <div class="ibox-body">
                <div class="row">
                    <div class="col-md-4 row mb-3">
                        <div class="col-md-5 font-weight-bold">Supplier:</div>
                        <div class="col-md-7">{{$purchase['supplier']}}</div>
                    </div>
                    <div class="col-md-4 row mb-3">
                        <div class="col-md-5 font-weight-bold">Created By:</div>
                        <div class="col-md-7">{{$purchase['created_by']}}</div>
                    </div>
                    <div class="col-md-4 row mb-3">
                        <div class="col-md-5 font-weight-bold">Updated By:</div>
                        <div class="col-md-7">{{$purchase['updated_by']}}</div>
                    </div>
                    <div class="col-md-4 row mb-3">
                        <div class="col-md-5 font-weight-bold">No. of Product:</div>
                        <div class="col-md-7">{{$purchase['no_of_products']}}</div>
                    </div>
                    <div class="col-md-4 row mb-3">
                        <div class="col-md-5 font-weight-bold">Created at:</div>
                        <div class="col-md-7">{{$purchase['created_at']}}</div>
                    </div>
                    <div class="col-md-4 row mb-3">
                        <div class="col-md-5 font-weight-bold">Updated at:</div>
                        <div class="col-md-7">{{$purchase['updated_at']}}</div>
                    </div>
                </div>
                <h6 class="m-b-20 m-t-20"><i class="fa fa-cubes"></i>Products</h6>
                <table id="products-table" class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Product Name</th>
                        <th>Product Code</th>
                        <th>Purchase Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($purchase['products'] as $product)
                        <tr>
                            <td>{{$product['product_id']}}</td>
                            <td>{{$product['product_name']}}</td>
                            <td>{{$product['product_code']}}</td>
                            <td>{{$product['unit_price']}}</td>
                            <td>{{$product['quantity']}}</td>
                            <td>{{$product['sub_total']}}</td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                    <tr>
                        <th colspan="4"></th>
                        <th>{{$purchase['total_quantity']}}</th>
                        <th>{{$purchase['total']}}</th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script src="{{asset('assets/js/datatables.min.js')}}" type="text/javascript"></script>
    <script type="text/javascript">
        let dataTable = $('#products-table').DataTable({
            pageLength: 10,
        });
    </script>
@endsection